### PR TITLE
KPI 11.4 - Research Max Validator Change Report

### PR DESCRIPTION
**Pull request by freakstatic**
I know this submission is really late but here it goes :)

### CODE REVIEW

**Review by bwhm — COMMENTED** [review]
A little late as you say, but lots of good info here!

It does look like the `era` duration is incorrect though? All the eras seem to be 1h, but not have the same amount of blocks in them!

I'll approve if I'm wrong, and grade the KPI now, but please fix if I'm correct!

**Comment by freakstatic** [comment]
Yeah you are right, I thought it was strange as well... it seems that was an error from my end, some blocks are not being associated with the era... 
I will fix it!

**Comment by freakstatic** [comment]
@bwhm I fixed it! 
Please check it

**Review by bwhm — APPROVED** [review]
LGTM!

**Pull request merged**
