### PR TITLE
05_12_2021_weekly_report_bounty_24.md

### PR DESCRIPTION
**Pull request by Arseniy2706**

### CODE REVIEW

**Comment by traumschule** [comment]
[Proposals 887](https://pioneer.joystreamstats.live/#/proposals/887)

**Comment by mochet** [comment]
this has the wrong proposal link @swasilenko can you please paste the correct one for this PR

**Comment by swasilenko** [comment]
@mochet but why is this a wrong link? as i see, everything is fine. if you go to proposal link and from there go to PR link, it will be the same PR

**Comment by mochet** [comment]
> @mochet but why is this a wrong link? as i see, everything is fine. if you go to proposal link and from there go to PR link, it will be the same PR

you're correct, sorry for confusion!

**Pull request merged**
