### PR TITLE
Bot project  for KPI 10.5 - (Telegram Bots)- Bitoven

### PR DESCRIPTION
**Pull request by bitoven-dev**
Approved Proposal links: https://testnet.joystream.org/#/proposals/35
Bots done: 3,4,5,7
@blrhc , @bwhm

### CODE REVIEW

**Comment by blrhc** [comment]
@bitoven-dev Great stuff, taking a look at these now!

**Comment by bwhm** [comment]
Adding in that we may not get a chance to test properly before the end of the week, at which point the API have been updated. Will test and evaluate towards the version at the time the KPI was made, so any changes regarded will be it's own KPI, and/or made by ourselves :)

**Comment by bedeho** [comment]
Great work!

**Comment by bwhm** [comment]
Providing some rough feedback here, as it's not yet time for grading of [KPI 11x](https://blog.joystream.org/constantinople-kpis/#current). 

#### General
The instructions provided are nice and easy, so I had no problem deploying and testing them. 

Because of the runtime upgrade I tested on an "old" version with a dev-chain. As the KPI was made while the "old" types were active, this will of course not matter.

**Note** Before posting, I tried on the current testnet, and it works fine :)


#### Specific

##### Proposals/`11.3`
As there are lots of paths here, I didn't try every possible proposal, outcome and failure.
- All the requested info, `proposalId, type, member.Id, member.Handle, Title, stage, result`, is provided
- The `result` could have been formatted a little better, but it works as requested.
- The one real issue I found applies only to (a) proposal(s) with a grace period, such as "Spending":

Example:
1. I create a Spending proposal, bot returns:
```
New proposal (2) created at block 1864.
 Type: Spending
 Proposer: memb3(305)
 Title:   #
 Stage: Active
 Result: {"Active":null}
```
2. I Approve it, and the bot posts:
```
Proposalid (2) status changed to "Finalized" at block 1867.
 Type: Spending
 Proposer: memb3(305)
 Title:   #
 Stage: Finalized
 Result: {"Approved":{"PendingExecution":null}}
```
Now, without taking the grace period in to account, it _immediately_ also posts:
```
Proposalid (2) failed to be executed at block 1877.
 Type: Spending
 Proposer: memb3(305)
 Title:   #
 Stage: Finalized
 Result: {"Approved":{"PendingExecution":null}}
```

Now, I had a 10 block grace period here, so it shouldn't have given me the result before reaching that block height. As all proposals, regardless of grace period, will have a separate event for execution (example for 0 grace period [here](https://testnet.joystream.org/#/explorer/query/1928111), this could be solved in a general way.
 
##### Council/`11.4`
- Works fine, and posts the following:
```
New council election for round 4 has been started at block 61. You can apply now!
...
Voting stage for council election has been started at block 81. You can vote now!
...
Revealing stage for council election has been started at block 91. Don't forget to reveal your vote!
...
 New council for round 4 has been elected at block 101.
```
- All with relevant links :)

##### Forum/`11.5`
- Works fine, and posts the following:
```
New category created: Test of new cat, Category ID: 12
...
New thread created: "New thread" by memb4 (id:306) in category "Test of new cat"
...
🤩 New post (id:188) by memb4 (id:306) in category "Test of new cat" at:
"New thread"
"12345678901234567890123456789012345..."
```

##### Channel/`11.7`
- Works fine, and posts the following:
```
New channel id created:1
Channel Title: My Channel
Member ID: 305
Member Handler: memb3
```

#### Summary
Although there could be some improvements in both implementation and the bot "posts", there is only one bug to speak of.

Feel free to submit more bots, and/or improvements within the deadline, and don't forgot to ask the Council for your just reward(s) :)

**Comment by bwhm** [comment]
@bitoven-dev 
As far as I can tell, you have not created any funding proposal(s) to get your reward for this. Do you want to request funding for these ASAP, or should I just grade and pay as is?

**Pull request merged**
