### PR TITLE
Bounties JSON Initial update

### PR DESCRIPTION
**Pull request by mochet**

### CODE REVIEW

**Review by bwhm — CHANGES_REQUESTED** [review]
This is a good start, but one important thing I immediately see needs fixed is that the link to the forum should be first. The reason for this, as explained [here](https://github.com/Joystream/community-repo/tree/master/bounties-overview#bounties-schema), is that we want the link from the website to go to the forum.


Related to this (I'm going to make a proposal for this), the Council needs to think about how a bounty is presented to the Community in the Forum. As (poorly) stated before, Jsgenesis makes the bounty issues primarily for the Council. It's the Councils role to make it clear what they expect, in terms of format, and workflow!

(Finally, I hope [this table](https://github.com/Joystream/community-repo/tree/master/bounties-overview#bounty-status) can be updated as well)

**Comment by mochet** [comment]
> This is a good start, but one important thing I immediately see needs fixed is that the link to the forum should be first. The reason for this, as explained [here](https://github.com/Joystream/community-repo/tree/master/bounties-overview#bounties-schema), is that we want the link from the website to go to the forum.
> 
> Related to this (I'm going to make a proposal for this), the Council needs to think about how a bounty is presented to the Community in the Forum. As (poorly) stated before, Jsgenesis makes the bounty issues primarily for the Council. It's the Councils role to make it clear what they expect, in terms of format, and workflow!
> 
> (Finally, I hope [this table](https://github.com/Joystream/community-repo/tree/master/bounties-overview#bounty-status) can be updated as well)

Have adjusted it. Will also adjust the table.

**Comment by mochet** [comment]
> > This is a good start, but one important thing I immediately see needs fixed is that the link to the forum should be first. The reason for this, as explained [here](https://github.com/Joystream/community-repo/tree/master/bounties-overview#bounties-schema), is that we want the link from the website to go to the forum.
> > Related to this (I'm going to make a proposal for this), the Council needs to think about how a bounty is presented to the Community in the Forum. As (poorly) stated before, Jsgenesis makes the bounty issues primarily for the Council. It's the Councils role to make it clear what they expect, in terms of format, and workflow!
> > (Finally, I hope [this table](https://github.com/Joystream/community-repo/tree/master/bounties-overview#bounty-status) can be updated as well)
> 
> Have adjusted it. Will also adjust the table.

Table is updated

**Review by bwhm — APPROVED** [review]
Looks great!

**Pull request merged**
