### PR TITLE
move governance files

### PR DESCRIPTION
**Pull request by traumschule**
[Proposal 917](https://pioneer.joystreamstats.live/#/proposals/917)

### CODE REVIEW

**Comment by mochet** [comment]
Regarding moving governance files:
- Do we really need a separate `council` folder? It could make some sense though for particular things.
- Things like the curation policy, warn/slash/fire rules feel like they should stay in the governance folder--these are things that the council has agreed on, and the council is responsible for updating and maintaing them. Even though the WGs have to follow the things, the council is the one that actually does the warn/slash/firing and ensures the curation policy is followed.
- I'm less certain about OKRs--these are things the council has agreed on and pays out via `spending proposals`

**Comment by mochet** [comment]
(I didn't realize the council folder already existed... maybe it could be combined with governance?)

Anything that reduces the initial set of folders I think would help in making it easier to navigate

**Comment by traumschule** [comment]
@mochet rebased.

**Comment by mochet** [comment]
> @mochet rebased.

great thank you!

**Pull request merged**
