### PR TITLE
Frontend implementation of the Community Bounty 19 (Validator Tool)

### PR DESCRIPTION
**Pull request by oleksanderkorn**
Bounty description: #161 
Demo: https://oleksanderkorn.github.io/joystream-live/
Backend for the Validator Tool: #242

### CODE REVIEW

**Comment by oleksanderkorn** [comment]
Frontend part fixing #161

**Comment by mochet** [comment]
This has been approved by the council and paid for via `spending proposal`: https://testnet.joystream.org/#/proposals/382
According to the bounty's details Jsgenesis now have 10 days to review this (@bwhm)

**Comment by bwhm** [comment]
FYI @oleksanderkorn,
The demo seems to be down (backend though)!

**Comment by oleksanderkorn** [comment]
> FYI @oleksanderkorn,
> The demo seems to be down (backend though)!

Hello @bwhm it has been moved to jsstats call please check it here: https://joystreamstats.live/validator-report

**Review by DzhideX — APPROVED** [review]
LGTM!

**Pull request merged**
