### PR TITLE
Create bounty-18-report-12.09.2021.md

### PR DESCRIPTION
**Pull request by ZAZIK3**

### CODE REVIEW

**Review by maxlevush — CHANGES_REQUESTED** [review]
@ZAZIK3
Put the table inside the file. The link does not suit us. Anyone can change the content inside a google document.
Also, don't use the commit link. Use the link to the file

**Review by maxlevush — APPROVED** [review]

**Comment by mochet** [comment]
Is there a proposal for this @ZAZIK3

**Comment by singulart** [comment]
Suggested changes seems to be implemented. PR is ready for merge

**Comment by mochet** [comment]
approved proposal: https://testnet.joystream.org/#/proposals/603

**Pull request merged**
