### PR TITLE
Create Council Round #21+22 - 08-09-2020 - Council Report.md

### PR DESCRIPTION
**Pull request by mochet**

### CODE REVIEW

**Comment by finnyfound** [comment]
Really detailed and comprehensive report.  Kudos!

**Comment by mochet** [comment]
This didn't get passed by vote via the first proposal, I've created another proposal for it here: https://testnet.joystream.org/#/proposals/88

Will update once it passes

**Comment by bedeho** [comment]
Fantastic work, I am blown away!

**Comment by mochet** [comment]
This was approved by the council: https://testnet.joystream.org/#/proposals/88

**Pull request merged**
