### PR TITLE
KPI 21.8: New folders structure

### PR DESCRIPTION
**Pull request by obuistov**
Slightly improved folder structure on top of what was done earlier: https://github.com/Joystream/community-repo/pull/293

### CODE REVIEW

**Comment by maxlevush** [comment]
Approved proposal https://testnet.joystream.org/#/proposals/566

**Review by bwhm — CHANGES_REQUESTED** [review]
Hey,

As stated in the [proposal](https://testnet.joystream.org/#/proposals/566), it's hard to review, but I see a couple things I'd like to "fix":
1. Keep the folder name consistent. Specifically:
`working-groups/curator_group` should be `working-groups/curator-group` (or `working_groups/curator_group`, but that would require a lot more changes).

if you want to use `camelCase.file` or `underscore_for.file` that's ok, but at least keep directories consistent?

2. Avoid spaces for both folders and files please. I think it's only files remaining here, but I'd still prefer changing them as well. Could be manual of course, as I suspect a script _may_ get in trouble here :)

3. Has the conventions been added?

**Comment by singulart** [comment]
improved the structure, removed spaces

**Comment by singulart** [comment]
Closing this one in favour of the future one after all others are merged

**Pull request closed without merging**
