### PR TITLE
WG Bot

### PR DESCRIPTION
**Pull request by singulart**
This PR is about a simple non-interactive notifier bot that updates the community about work group events. 

See https://pioneer.joystreamstats.live/#/proposals/993

### CODE REVIEW

**Comment by traumschule** [comment]
Thanks, [looks great](https://discord.com/channels/811216481340751934/812344874099277824/937762709091532841)!
- Test revealed dependency on node 16+.
- Please add this setup step: `git submodule update --init`
- If `ts-node` is needed add it as dev dependency.
```
$ git clone https://github.com/singulart/community-repo -b tooling/wg-bot wg-bot
$ cd wg-bot/scripts/wg-bot
$ git submodule update --init
Submodule 'lib' (https://git.joystreamstats.live/Operations/joystream-lib) registered for path '../report-generator/src/lib'                                   
Submodule 'wg-bot-lib' (https://git.joystreamstats.live/Operations/joystream-lib) registered for path 'src/lib'                                                
Cloning into '/home/joystream/wg-bot/scripts/report-generator/src/lib'...                                                                                      
Cloning into '/home/joystream/wg-bot/scripts/wg-bot/src/lib'...                                                                                                
Submodule path '../report-generator/src/lib': checked out 'dd6872ca55db450d6ea4ccf869392d26d6d9774c'                                                           
Submodule path 'src/lib': checked out 'a6974a9ae485c68d99a6ebd913df3624780913f0'
$ volta run --node 16 yarn
yarn install v1.22.17
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning "@joystream/types > @polkadot/keyring@7.3.1" has incorrect peer dependency "@polkadot/util@7.3.1".
warning "@joystream/types > @polkadot/keyring@7.3.1" has incorrect peer dependency "@polkadot/util-crypto@7.3.1".
[4/4] Building fresh packages...
Done in 1.28s.
$ volta run --node 16 yarn build
$ tsc --build tsconfig.json                                                                                                                                    
node_modules/@polkadot/types/create/registry.d.ts:7:22 - error TS2589: Type instantiation is excessively deep and possibly infinite.                           
                                                                                                                                                               
7 export declare class TypeRegistry implements Registry {

node_modules/@polkadot/api/augment/events.d.ts:31:32 - error TS2552: Cannot find name 'AugmentedEvent'. Did you mean 'AugmentedEvents'?                                                                                                                                                                                       
...
Found 254 errors.

$ volta run --node 16 yarn add -D ts-node
$ volta run --node 16 ./node_modules/.bin/ts-node src/index.ts
Bot logged in successfully
[Joystream] Opening websocket ws://localhost:9944
[Joystream] Connected to ws://localhost:9944
Discord.js client ready
4266142 operationsWorkingGroupAlpha StakeIncreased 0
4266182 operationsWorkingGroupAlpha OpeningAdded 25
```

Minor change to `src/index.ts` to load token from `/src/config.ts` (with `export const discordBotToken = ''` as default)
```
-import { workingGroups } from './config'                                                                                                                      
+import { discordBotToken, workingGroups } from './config'                                                                                                     
                                                                                                                                                               
                                                                                                                                                               
-const discordBotToken = process.env.TOKEN || undefined // environment variable TOKEN must be set                                                              
+if (!discordBotToken.length) {                                                                                                                                
+  console.error(`Please configure 'discordBotToken' in src/config.ts.`)                                                                                               
+  process.exit(1)                                                                                                                                             
+}
```

**Comment by traumschule** [comment]
@bwhm can you please review. [looks good](https://discord.com/channels/811216481340751934/933726271832227911/938500421759168593) in production and does not seem malicious.

**Review by bwhm — APPROVED** [review]
LGTM!

**Comment by swasilenko** [comment]
https://testnet.joystream.org/#/proposals/1113 approved and reviewed, can be merged

**Pull request merged**
