### PR TITLE
discord bot example

### PR DESCRIPTION
**Pull request by traumschule**
To test it, run `yarn && yarn run start`.

For details see #123

### CODE REVIEW

**Comment by traumschule** [comment]
@bwhm does this meet your expectations?

**Comment by mochet** [comment]
This appears to fulfill all the requirements mentioned by the bounty (for milestones 2+3), can you please submit a spending proposal @traumschule and once that is approved I'll request a review from @bwhm

**Comment by mochet** [comment]
This was approved via spending proposal: https://testnet.joystream.org/#/proposals/27

**Review by bwhm — COMMENTED** [review]
I wasn't set as reviewer here, but since I was already reviewing the related #131, and the spending was approved, I'm taking the liberty!

There are some things missing here, and upon trying, with #131 as well.

I followed the steps, modified the token and replaced `@joystream-bot` with `@joystreamTestBot`, but it didn't work...

Also, perhaps not very important, but I would prefer having the typescript code compiled to js, and then ran.

**Comment by bwhm** [comment]
@traumschule
:)

**Comment by traumschule** [comment]
so it`s `yarn run build && yarn run start` now

**Comment by traumschule** [comment]
No longer relevant.

**Pull request closed without merging**
