### PR TITLE
Community Bounty #11 - "Community Repo Banner"

### PR DESCRIPTION
**Pull request by vulxbuga**

### CODE REVIEW

**Comment by bwhm** [comment]
Hey,

Thanks for your contribution!
The bounties system has not been made properly yet, but:

- Did the council approve this?
- If so, where?
- If not, you need the Council to approve a spending proposal, and have them ask for a review before grading!

These rules will (hopefully) be made more clear in the next few days!

**Comment by vulxbuga** [comment]
> Hey,
> 
> Thanks for your contribution!
> The bounties system has not been made properly yet, but:
> 
> * Did the council approve this?
> * If so, where?
> * If not, you need the Council to approve a spending proposal, and have them ask for a review before grading!
> 
> These rules will (hopefully) be made more clear in the next few days!


Hey! Martin
council first approved my banner
but I indicated 250,000 tokens 
https://testnet.joystream.org/#/proposals/154

then I resent the request to add more tokens (as indicated in the proposal for this bounty)
https://testnet.joystream.org/#/proposals/161
but the council abstained

But it's not a problem
I want to create a design for your project
and participate in various events

I think that my first proposal (can be considered final)
https://testnet.joystream.org/#/proposals/154

Thank you for writing

**Comment by bwhm** [comment]
Thanks!

Once we have approved three, we'll grade them all :)

**Comment by mochet** [comment]
Hi! thanks for entering, please make sure to post your entry on the forums: https://testnet.joystream.org/#/forum/threads/344

**Comment by vulxbuga** [comment]
> Hi! thanks for entering, please make sure to post your entry on the forums: https://testnet.joystream.org/#/forum/threads/344

Thank you for writing!
did it right now

**Comment by mochet** [comment]
Approved via rolling update: https://testnet.joystream.org/#/proposals/201

**Pull request merged**
