### PR TITLE
Create KPI_09-6-initial_sprocket.md

### PR DESCRIPTION
**Pull request by mochet**

### CODE REVIEW

**Comment by mochet** [comment]
this was approved by council: https://testnet.joystream.org/#/proposals/110

**Review by bwhm — CHANGES_REQUESTED** [review]
Hey @mochet,

Unfortunately, I think there are a couple of things still missing for this to work as you intend.
- There are no reactions on the forum, and the "forum 2.0" will not go out before pioneer 2.0 is out, so we're talking ~3 months...
- I actually tested uploading an image on the staging network, and although it works, it's not supported in the [UI](https://play-staging.joystream.app/video/1613)
- It will be used to store assets for videos in channel in the next release, but it doesn't really belong on a video platform to have a bunch of still images...?
- Playlists will be enabled at the runtime level in next release, but atlas will likely lag behind
- As you say, forum in CLI is not there currently, and although it's "easy" to implement, it's honestly not worth it. The UX will be horrible! However, making a script is even easier :)

If you think images is the way to go, I'd say that atm, you'd have to rely on "existing" forum functionality unfortunately. I believe you can post images here, but it would remove a lot of the fun...
My thinking is that short gif-like videos may be easier at this point?

(By "Request changes", I mean to say that I think it requires some changes before this will work in a good way)

**Comment by mochet** [comment]
> Hey @mochet,
> 
> Unfortunately, I think there are a couple of things still missing for this to work as you intend.

Since I wrote this the Runtime DAOs issue was made: https://github.com/Joystream/joystream/issues/2068
That may be a far more feasible manner of doing this whole idea, but obviously depends on whether it actually gets developed and how long it would take. It sounds like it provides a way of doing basically the entire concept of Sprocket from start to finish without having to use the forum or use scripts and because it is its own DAO it makes applying rulesets and management a whole lot easier and also means you don't have to rely so much on scripts and tools to get the job done (and also DAOs are probably more interesting for users, since they can basically "invest" in the ones they like, participate and get financial rewards).

It also means that it is much easier to quantify what the "value" of Sprocket is, whereas if it uses the forum and scripts this is a lot more difficult to do.

> * It will be used to store assets for videos in channel in the next release, but it doesn't really belong on a video platform to have a bunch of still images...?

Agreed. I was hoping to start with images and then gradually expand to media types, but as you suggested, maybe short clips from public domain videos would work well. 5-10 seconds or something like that.

The only issue with anything besides still images is that the technical knowledge required for users increases. Image manipulation tools are fairly simple and widespread but clipping videos is a bit more complex (even if there are many tools around, formatting requirements make it a complex task). In my mind, the more barriers for entry, the less submissions, but that is mainly a viewpoint regarding building up a community of people who are continuously posting. If the community size was already sufficient then it wouldn't be as big of an issue.



> * There are no reactions on the forum, and the "forum 2.0" will not go out before pioneer 2.0 is out, so we're talking ~3 months...

This is unfortunate, I'll have a think about some alternative voting mechanisms.

One could be a dedicated Telegram channel, where a bot can be used for voting. This is less than ideal since it wouldn't encourage forum use (but on the bright side, it would still encourage people to upload and view content)

**Comment by bwhm** [comment]
The runtime DAOs should be a good way to run these kinds of things - for sure!

---

Wrt to video vs images, that is certainly true, but it's certainly more in line with the project, and arguably more fun to observe. I should add that still images actually works already, to some extent. As can be seen [on the staging network atlas](https://play-staging.joystream.app/) - ID 1613.

---

Yes, that is one way. Another relatively easy one would be token voting :)

**Comment by mochet** [comment]
> Yes, that is one way. Another relatively easy one would be token voting :)

Yes that might work, would you create an address for each entry and then just tally the amount of tokens once completed?

**Comment by mochet** [comment]
This was launched: https://testnet.joystream.org/#/forum/threads/442?replyIdx=1
So I guess it can be merged now?

**Comment by traumschule** [comment]
> this was approved by council: https://testnet.joystream.org/#/proposals/110

The current link is https://testnet.joystream.org/#/proposals/historical/110

Since this was approved a long time ago when the council was much smaller I suggest to resubmit this as a task to Operations to assess if this is technically feasible and estimate costs for a prototype.

**Comment by mochet** [comment]
approved by this rolling update proposal: https://testnet.joystream.org/#/proposals/501

**Pull request merged**
