### PR TITLE
Deleted

### PR DESCRIPTION
**Pull request by laura2727**

### CODE REVIEW

**Comment by maxlevush** [comment]
I think it can be merged

**Review by bwhm — CHANGES_REQUESTED** [review]
Still some smaller issues from me. I think some has been raised before, but I don't remember where :(

1. BM should not be a Curator:
> For this, the Bounty will be allocated 2 people from the group of curators, 1 curator and 1 curator (Bounty manager) reward for the work of the curator $ 25, reward for the work of the Bounty manager $ 50 for the reporting period a week, provided that their work is done with high quality and will be accepted. They will be informed and must be qualified to ensure that the video does not violate any license, copyright or conditions. The curator appoints the lead.



As stated previously, the person grading the value of the video (ie. the BM), should NOT be a current curator. The reason for this is that otherwise we may have conflicts of interest.

The Curator or Curators assigned shall ensure and enforce that no videos that violates any licenses or terms will sent forward for grading by the BM. So their scope is limited solely to that, and doesn't have to care about if a video is too short/long, or has a bad resolution, or that the participants hasn't gone over any limits, etc.

The BM will then not have to be concerned with that part, and can stick to grading videos based on "quality".

2. Create a specific format for the participants and the Curator(s):
> It is the responsibility of the curator to create a new list / table of only approved contributions, published in any convenient way, where he adds all videos that need to be rated by BM.
> This list should include (video id, username, forum link, rating / payout).

To make it easier for yourselves, require a set format for participants. Examples:

Either a table (not that one ofc)

* Member ID/Handle: `1337/@me`
* Channel ID/Handle `1/coolchannel`
|Video ID|handle| ... |
|:-------:|:------:|---|
|1            |@me   |---|

...somehing like:

- **Handle**: `@me` 
- **Channel ID**: `1337`
- **Video IDs**: `1,2,3,..`
- **etc.**: `...`
... or something else entirely, as long as it's consistent and has all the info required.

It may be beneficial to use a markdown table, so that you can easily convert it to excel, json or something with tableconvert.com for the Curator(s) when sending to the BM.

3. Revise language of this:
> If bids are rejected they do not need to be contacted individually, users submitting videos for this award are responsible for checking the status.

`bids` not the best word perhaps?

5. Separate between readers!
I think the latter parts of this document targets the "end user", namely the participants, whereas the latter targets the BM, Curators and the Council. To make it easier for the readers, perhaps make one document SOLELY for the participants, as they don't really care what happens in between them submitting something, and the pay out :)

Overall, very good work though!

**Comment by singulart** [comment]
@laura2727 please address the comments above. thanks!

**Comment by laura2727** [comment]
> @laura2727 please address the comments above. thanks!

The comments above have long been answered in discord, thank you.

**Comment by singulart** [comment]
Laura, can you please ease my job a little by summarising here what was the final decision/outcome of the discussion? I am trying to make all PRs like this one merged ASAP and need your help.

**Comment by laura2727** [comment]
> Laura, can you please ease my job a little by summarising here what was the final decision/outcome of the discussion? I am trying to make all PRs like this one merged ASAP and need your help.


Yes, the appointment of the BM for this bounty was voted on and the consuls approved these rules!

**Pull request closed without merging**
