### PR TITLE
Update report generator to joystream/types 0.14

### PR DESCRIPTION
**Pull request by freakstatic**

### CODE REVIEW

**Comment by mochet** [comment]
@freakstatic is this ready for review? Did you want to submit it as a text/spending proposal?

**Comment by freakstatic** [comment]
I don't know if this is worth creating a text proposal since it was only updating the "types" version and delete commented code

**Comment by singulart** [comment]
LGTM

**Comment by singulart** [comment]
This PR is obsolete and shouldn't be even merged

**Comment by mochet** [comment]
This PR has been indicated as obsolete and I also checked with the initial creator of this PR and they agreed. Closing.

**Pull request closed without merging**
