### PR TITLE
Create bounty10_crash_payouts.csv

### PR DESCRIPTION
**Pull request by mochet**

### CODE REVIEW

**Comment by mochet** [comment]
this can be merged, it was uploaded here due to size constraints on the forums

**Review by bwhm — APPROVED** [review]
Tyty!

Making the payouts now.

**Comment by bwhm** [comment]
Thanks!
Does that mean these are already paid? So I'll refund tokens -> increase pool?

**Comment by bwhm** [comment]
Paid out [here](https://testnet.joystream.org/#/explorer/query/0x138e7bc7188f4b76b3b9210ecd8728935e48775ae14b455ec87a378d63df0654)

**Comment by mochet** [comment]
> Paid out [here](https://testnet.joystream.org/#/explorer/query/0x138e7bc7188f4b76b3b9210ecd8728935e48775ae14b455ec87a378d63df0654)

oh I just noticed the tokens in the account! they were minted from a `spending proposal` so not sure what to do with them now (https://testnet.joystream.org/#/proposals/50)... there are some additional payments that will need to be made so I could just use these tokens + create another spending proposal if needed.

**Comment by bwhm** [comment]
Ooops!
Feel free to do that, or simply burn them :)

**Pull request merged**
