### PR TITLE
Upload survey results

### PR DESCRIPTION
**Pull request by lopegor**
Hey Everyone! Here's the summary of the survey.

### CODE REVIEW

**Review by bwhm — CHANGES_REQUESTED** [review]
Hey,

Not to be difficult, but some notes:
1. I need an approved proposal to merge
2. I think you need to move the results to a more "appropriate" location
3. Although gifs are funny, not sure they should be there :)

**Comment by mochet** [comment]
This was approved on this proposal: https://testnet.joystream.org/#/proposals/195 (I think before the gifs were added haha)

@lopegor can you please remove the gifs and move this to the /community-repo/community-contributions/ folder and create a folder titled something like `fm-survey` which contains the report? after that I'll request re-review

**Comment by traumschule** [comment]
I suggest to give @lopegor a bit more time to make the requested changes.

**Comment by mochet** [comment]
> I suggest to give @lopegor a bit more time to make the requested changes.

Yes, that's fine there's no rush.

**Comment by mochet** [comment]
This was approved via this rolling update proposal: https://testnet.joystream.org/#/proposals/501
Changes made:
- removed 2 GIFs
- renamed file
- moved to an appropriate directory

**Pull request merged**
