### PR TITLE
decaf_1883.md

### PR DESCRIPTION
**Pull request by Decafall**
26.01.2022 atlas wasn't working so all of my newly uploaded videos were gone. Also I could not upload new videos that day, so I reuploaded everything a day after.

### CODE REVIEW

**Comment by swasilenko** [comment]
@Decafall hello!! what is your telegram handle? we try to find you and can't... please join the group https://t.me/JoystreamRussian

**Comment by swasilenko** [comment]
@Decafall also please add .md to the end of the name of your file

**Comment by Decafall** [comment]
Hi! My telegram handle is @alldecaf

Пт, 28 янв. 2022 г. в 15:35, swasilenko ***@***.***>:

**Comment by Decafall** [comment]
> @Decafall hello!! what is your telegram handle? we try to find you and can't... please join the group https://t.me/JoystreamRussian

Hi! 
Telegram: @alldecaf
Discord: decaf#8302

**Comment by swasilenko** [comment]
https://pioneer.joystreamstats.live/#/proposals/1093 approved, can be merged

**Pull request merged**
