### PR TITLE
merged bots into one

### PR DESCRIPTION
**Pull request by bwhm**
@mochet @bitoven-dev 

I can't assign you as reviewers (for the former, because I forgot to grant you MOAR permissions), but won't merge until approved :)

### CODE REVIEW

**Comment by bwhm** [comment]
hmm. @bitoven-dev 
Perhaps I should instead make the PR to your fork?

**Comment by bitoven-dev** [comment]
> 
> 
> hmm. @bitoven-dev
> Perhaps I should instead make the PR to your fork?

Hi @bwhm  , I actually rather new for this Github thing especially on pull request. From my understanding, I need to review and approve the code? If yes and for current situation (that I don't have reviewer permission), maybe I will just post here that I have reviewed and approved, is that ok?
Also maybe I will also put some corrections on the code, what is the best way to do it?

**Comment by mochet** [comment]
We never really had a process for proposing improvements implements so far, I created a thread to discuss that here: https://testnet.joystream.org/#/forum/threads/102?replyIdx=1

So I'm not sure if this would require a proposal created, as its an improvement? I'll see if anyone gives feedback and create a proposal once the new council round starts to deal with this kind of situation.

**Comment by bwhm** [comment]
@mochet 

As the last Council Secretary: approval to merge?

See tlgrm for info :D
(also invited as outside collaborator with `triage`)

**Comment by mochet** [comment]
> @mochet
> 
> As the last Council Secretary: approval to merge?
> 
> See tlgrm for info :D
> (also invited as outside collaborator with `triage`)

I think as its an improvement it can be approved

**Pull request merged**
