### PR TITLE
Correct tokenomics salaries

### PR DESCRIPTION
**Pull request by traumschule**
Fix bug that lead to incorrect WG spending.
[Proposal 796](https://pioneer.joystreamstats.live/#/proposals/796)

### CODE REVIEW

**Comment by mochet** [comment]
@bwhm can you please review the code in this

**Review by bwhm — APPROVED** [review]
Looks fine to me :)

**Comment by bwhm** [comment]
Would be good to hold merge until @DzhideX can do a quick review :)

**Comment by bwhm** [comment]
Oh wait - I do have one comment.

I think we should have _everything_ that uses the api in an API directory, that includes:
- Examples
- Bots
- Council Report generator
- xyz.

Then, you can avoid having to build the types 10 times in a single repo...

**Review by DzhideX — APPROVED** [review]
LGTM!

**Comment by traumschule** [comment]
> I think we should have _everything_ that uses the api in an API directory, that includes:

@bwhm Sure, fine with me. Is it ok to merge this first and run the new rule by the council first?

**Pull request merged**
