### PR TITLE
Create initial template files for storage + curator evaluation

### PR DESCRIPTION
**Pull request by mochet**

### CODE REVIEW

**Comment by freakstatic** [comment]
This seems good!

**Comment by mochet** [comment]
I've also added the curator template to this PR, for the actual reports I'll create separate PRs.

**Comment by mochet** [comment]
This was approved by council here: https://testnet.joystream.org/#/proposals/14

**Review by bwhm — APPROVED** [review]
:+1:

**Review by blrhc — APPROVED** [review]

**Comment by blrhc** [comment]
@mochet Do you have merge permissions?

**Comment by mochet** [comment]
> @mochet Do you have merge permissions?

No I don't think I have those permissions.

**Comment by blrhc** [comment]
@bwhm Is there a reason this can't be merged at the moment?

**Pull request merged**
