### PR TITLE
KPI 19 SP2 initial version of Storage provider sanctions

### PR DESCRIPTION
**Pull request by singulart**

### CODE REVIEW

**Comment by maxlevush** [comment]
I think its not for 'operations" folder @mochet

**Comment by mochet** [comment]
@singulart can you please change the folder, this is currently put in the `operations` folder. It could be put in `rules` instead

**Comment by singulart** [comment]
@mochet Done!

**Comment by traumschule** [comment]
There are several commits with the same description. Would it be possible to squash them into one?

**Comment by singulart** [comment]
> There are several commits with the same description. Would it be possible to squash them into one?

Done

**Comment by singulart** [comment]
@mochet I addressed all comments. I guess this can be merged?

**Comment by singulart** [comment]
Proposal: https://pioneer.joystreamstats.live/#/proposals/541

**Pull request merged**
