### PR TITLE
KPI 31.I-7 Joystream Node Issues

### PR DESCRIPTION
**Pull request by traumschule**
https://blog.joystream.org/sumer-kpis/#31.I-7
[README](https://github.com/Joystream/community-repo/blob/1fd5b503f65d23b72931e992b49de30406552c5a/council/kpi/sumer/31.I-7/README.md)

### CODE REVIEW

**Comment by mochet** [comment]
Was there a proposal for this?

**Comment by traumschule** [comment]
@bwhm blocks.json is 23mb and Rewards.md is 19mb. is it necessary to merge them?

**Comment by swasilenko** [comment]
proposal https://testnet.joystream.org/#/proposals/913 approved, PR can be merged

**Comment by bwhm** [comment]
> @bwhm blocks.json is 23mb and Rewards.md is 19mb. is it necessary to merge them?

Naah, that's too much...

**Comment by traumschule** [comment]
> > @bwhm blocks.json is 23mb and Rewards.md is 19mb. is it necessary to merge them?
> 
> Naah, that's too much...

Now total is 6mb.

**Pull request merged**
