### PR TITLE
Community Bounty #11 - new banner (updated)

### PR DESCRIPTION
**Pull request by CheOmsk**

### CODE REVIEW

**Comment by bwhm** [comment]
Hey,

Thanks for your contribution!
The bounties system has not been made properly yet, but:
- Did the council approve this?
- If so, where?
- If not, you need the Council to approve a spending proposal, and have them ask for a review before grading!

These rules will (hopefully) be made more clear in the next few days!

**Comment by CheOmsk** [comment]
> Hey,
> 
> Thanks for your contribution!
> The bounties system has not been made properly yet, but:
> 
> * Did the council approve this?
> * If so, where?
> * If not, you need the Council to approve a spending proposal, and have them ask for a review before grading!
> 
> These rules will (hopefully) be made more clear in the next few days!

Hello! The vote was taken here: https://testnet.joystream.org/#/proposals/160
The Council decided to postpone the decision and additionally discuss the format of the creative bounty: https://testnet.joystream.org/#/forum/threads/286

**Comment by mochet** [comment]
Hi! thanks for entering, please make sure to post your entry on the forums: https://testnet.joystream.org/#/forum/threads/344

**Comment by mochet** [comment]
Approved via rolling update: https://testnet.joystream.org/#/proposals/201

**Pull request merged**
