### PR TITLE
Create Joystream Sticker Competition Report.md

### PR DESCRIPTION
**Pull request by mochet**

### CODE REVIEW

**Comment by freakstatic** [comment]
Great work! 👍

**Comment by mochet** [comment]
this was approved by council: https://testnet.joystream.org/#/proposals/126

**Review by bwhm — APPROVED** [review]
Thanks!

As you point out, it's kind of a problem that the stickers aren't made available here, as per the rules in #52, they won't get funded through increased pool...

**Comment by mochet** [comment]
> Thanks!
> 
> As you point out, it's kind of a problem that the stickers aren't made available here, as per the rules in #52, they won't get funded through increased pool...

thanks for mentioning that I guess I'll have to figure out a way to upload them on here

**Pull request merged**
