### PR TITLE
KPI 14.12 API Scripts Maintenance

### PR DESCRIPTION
**Pull request by singulart**
Added basic documentation
Ensured every single script is working
Updated types

### CODE REVIEW

**Comment by maxlevush** [comment]
@bwhm review please

**Comment by maxlevush** [comment]
No ``text proposal`` was created for this

**Comment by singulart** [comment]
@DzhideX can you please review this?

**Comment by singulart** [comment]
Proposal https://testnet.joystream.org/#/proposals/596

**Pull request merged**
