### PR TITLE
add joystream-leaderboard-bot

### PR DESCRIPTION
**Pull request by agrafen**

### CODE REVIEW

**Review by singulart — APPROVED** [review]
LGTM

**Comment by agrafen** [comment]
Hi! I update the bot and add discord support.

**Comment by traumschule** [comment]
This has been awarded and can be merged: https://pioneer.joystreamstats.live/#/proposals/335

**Comment by mochet** [comment]
> This has been awarded and can be merged: https://pioneer.joystreamstats.live/#/proposals/335

This has to be reviewed by JSG before merging as it contains code.

@bwhm

**Review by DzhideX — APPROVED** [review]
If I'm being nit-picky, I'd say:

- I've noticed a grammar mistake/oversight in `botService.ts`, line 52. Instead of "Don't" maybe we could write "Couldn't". I haven't noticed any other such problems but it would be great if you could just make sure there aren't any other ones.
- Possibly delete the commented out functionality (seems to be mostly console logs)?

Otherwise, great work! :)

**Comment by singulart** [comment]
@mochet this was reviewed by JSG user @DzhideX, assigning this to @bwhm as ready to merge.

**Pull request merged**
