### PR TITLE
Implementation of Joystream Scoring Periods Telegram/Discord BOT

### PR DESCRIPTION
**Pull request by oleksanderkorn**
Proposal link: https://testnet.joystream.org/#/proposals/519

Telegram bots responses:
image

Discord bot response:
image

Discord channel with the integrated bot: https://discord.gg/YDdEVD9R

Telegram channels where bots already added: https://t.me/JoyStreamOfficial, https://t.me/JoystreamRussian 
Telegram Bot Links: 
- Russian: https://t.me/js_scoring_bot 
- English: https://t.me/joystream_scoring_bot

### CODE REVIEW

**Comment by mochet** [comment]
This is code so I am unable to merge. Awaiting review from @bwhm

**Comment by bwhm** [comment]
As this is for the unofficial telegram group (I presume), go ahead :)

**Comment by oleksanderkorn** [comment]
> As this is for the unofficial telegram group (I presume), go ahead :)

It is also for discord, and is already added to joystream server.

**Comment by singulart** [comment]
Seems @bwhm agreed to merge

**Pull request merged**
