### PR TITLE
Move old council reports into archive folder

### PR DESCRIPTION
**Pull request by mochet**

### CODE REVIEW

**Comment by mochet** [comment]
A proposal will be created to approve these changes, I'll combine a few changes into a single proposal to save time. I'll post the proposal here once it is completed.

**Comment by mochet** [comment]
This was approved by council here: https://testnet.joystream.org/#/proposals/14

**Review by bwhm — APPROVED** [review]

**Comment by bwhm** [comment]
Not sure why this file has been added to `gitignore`?

**Comment by mochet** [comment]
> Not sure why this file has been added to `gitignore`?
> 
> @mochet
> Will merge if you confirm it's intentional :)

I think I just fixed it, sorry there was a bit of confusion with gitignore handling on my part.

**Review by bwhm — APPROVED** [review]
:+1:

**Pull request merged**
