### PR TITLE
Bot fixes for #36

### PR DESCRIPTION
**Pull request by traumschule**
Bot improvements requested in #36.

### CODE REVIEW

**Comment by bwhm** [comment]
FYI @traumschule 
You need to create a spending proposal if you want any rewards for this :)

If it's just meant as an improvement to #36, without any rewards expected, I'll review it!

**Comment by traumschule** [comment]
Closing in favor of #47

**Comment by traumschule** [comment]
Since #47 was closed, reopening to apply fixes.

**Comment by traumschule** [comment]
@bwhm shall we add your recent fix here?

**Comment by bwhm** [comment]
It's a simply one!
In [package.json](https://github.com/Joystream/community-repo/blob/1d8ce0f3b596a337a35bd1a6dbfccf230f85e9aa/community-contributions/joystreamtelegrambot/package.json#L26)
`    "@joystream/types": "^0.13.1",`
-> 
`    "@joystream/types": "^0.14.0",`

**Comment by traumschule** [comment]
Updated, rebased and tested.

**Pull request closed without merging**
