### PR TITLE
WG Report + Tasks

### PR DESCRIPTION
**Pull request by mochet**

### CODE REVIEW

**Review by bwhm — COMMENTED** [review]
Storage WG Tasks

Are these questions for me, or the Lead?
My guess is that all of them run their storage nodes on a VPS, so stats should be easy to collect.

The rest looks good!

**Comment by mochet** [comment]
> Storage WG Tasks
> 
> Are these questions for me, or the Lead?
> My guess is that all of them run their storage nodes on a VPS, so stats should be easy to collect.
> 
> The rest looks good!

These are all for the lead, it was a bit difficult to come up with tasks for the storage WG since its a bit limited to just running a server at the moment, so I guess if we identify as much as we can about the servers (like bandwidth use) it would be useful!

**Comment by bwhm** [comment]
@mochet 
I think the proposal is missing here!

**Comment by mochet** [comment]
Approved via rolling update: https://testnet.joystream.org/#/proposals/201

**Pull request merged**
