### PR TITLE
Founding Member Survey

### PR DESCRIPTION
**Pull request by andybut**

### CODE REVIEW

**Review by bwhm — CHANGES_REQUESTED** [review]
Thanks for this!

I'll ask @blrhc to review the results themselves, but I have a few small requests:
- Please don't use spaces in folder and file names. Something like `founding-member-survey` is preferable.
- Could you move to folder somewhere else than the root directory? I think `community-contributions` would be ok, before I make a new kpi this week about organizing this repo!

**Review by blrhc — APPROVED** [review]
Thanks for handling this initiative @andybut 
We will be introducing regular Jsgenesis-managed surveys for Founding Members and roles (likely this week) and the data you have collected in the community survey will be useful in honing down which further questions we should be asking in those :)

**Comment by mochet** [comment]
@andybut can you please create a `text proposal` for these changes so that they can be merged. Thanks.

**Comment by mochet** [comment]
Proposal approved: https://testnet.joystream.org/#/proposals/414
merging

**Pull request merged**
