### PR TITLE
Polkadot-JS extension browser test

### PR DESCRIPTION
**Pull request by traumschule**
See #32

### CODE REVIEW

**Comment by bwhm** [comment]
Hey @traumschule 
Remember to make a spending request from the council once you're done!

**Comment by mochet** [comment]
The proposal for this has been approved: https://testnet.joystream.org/#/proposals/87
There is some additional work that has already been done that has to be added to this PR, I will request review as soon as its added

**Comment by traumschule** [comment]
Ready for review

**Review by bwhm — COMMENTED** [review]
As this is approved, I'll grade it as such.

#### Success event 1
`OS and Browser tests performed `

- Although the MacOS isn't included explicitly, I'm going to assume it works just as well on the aforementioned browsers.
- Additionally, Android test is included, which is nice :)

#### Success event 2
`Cross device tests performed`

- Nothing mentioned.

#### Success event 3
`Functionality tests performed`


- What keypair types are supported
-> ✅ 
- What are the password requirements
-> ✅ 
- Will a key generated for a specific chain/runtime work for other chains
-> ✅ 
- Can you import raw seeds, mnemonic seeds and/or jsons
-> ❎ 
- Can you create new seeds and or jsons
-> ❎ 
- Can you export seeds and or jsons
-> ❎ 

---

Reading the issue + report gives the impression that the testing has been more thorough than the report indicates. 

Please remember that someone reading this report may not be aware of the context, and will probably find it confusing. Please be more explicit, and answer all the questions with as much details as required, and note what is still unknown or impossible to know.

As it appears this is at least partially tested, I'll allow 48h hours more for adding the results.

**Comment by bwhm** [comment]
@traumschule ^^^

**Comment by traumschule** [comment]
> * Although the MacOS isn't included explicitly, I'm going to assume it works just as well on the aforementioned browsers.

Did you look at [this version](https://github.com/Joystream/community-repo/blob/ab689a9af2196bdb4c694ce4eb6b7486bbba22de/community-contributions/miscellaneous_reports/Polkadot%20JS%20Extension.md)? Under the headline `MacOS / iOS` it is clearly said that there is no extension for Safari available for download.

> #### Success event 2
> `Cross device tests performed`
> 
> * Nothing mentioned.

It is unclear how to perform this test. Is this something about cloud features? Please define steps.
 
> * Can you import raw seeds, mnemonic seeds and/or jsons

See `Add via JSON file` and `Import raw seed, mnemonic`

> * Can you create new seeds and or jsons

See `Create new seed `

> * Can you export seeds and or jsons

See `Backup seeds and or JSON file`

> Reading the issue + report gives the impression that the testing has been more thorough than the report indicates.

It seems that the wording used in the report is not understood although it covers exactly above questions.

> Please remember that someone reading this report may not be aware of the context, and will probably find it confusing. 

Above report tries to answer exactly all functions that are asked for. Not more.

> Please be more explicit, and answer all the questions with as much details as required, and note what is still unknown or impossible to know.
> 
> As it appears this is at least partially tested, I'll allow 48h hours more for adding the results.

This seems to be a matter of words only. If it helps I will paste the questions into the report directly.

**Comment by traumschule** [comment]
@bwhm Hope that helps.

**Comment by mochet** [comment]
I rerequested review as it looks like issues have been sorted.

**Comment by bwhm** [comment]
> > * Although the MacOS isn't included explicitly, I'm going to assume it works just as well on the aforementioned browsers.
> 
> Did you look at [this version](https://github.com/Joystream/community-repo/blob/ab689a9af2196bdb4c694ce4eb6b7486bbba22de/community-contributions/miscellaneous_reports/Polkadot%20JS%20Extension.md)? Under the headline `MacOS / iOS` it is clearly said that there is no extension for Safari available for download.
> 

Yes, but your report implies that the other browsers aren't supported either :)
I know that is not the case, but someone else reading this might get confused.

> > #### Success event 2
> > `Cross device tests performed`
> > 
> > * Nothing mentioned.
> 
> It is unclear how to perform this test. Is this something about cloud features? Please define steps.

If I'm logged in, eg. on firefox, get the extension, and log in on another device (same OS or not), do I need to import the seed again or not?

So yes, about cloud features :)

> > * Can you import raw seeds, mnemonic seeds and/or jsons
> 
> See `Add via JSON file` and `Import raw seed, mnemonic`
> 
> > * Can you create new seeds and or jsons
> 
> See `Create new seed `
> 
> > * Can you export seeds and or jsons
> 
> See `Backup seeds and or JSON file`
 
I don't know what happened here! It was here all along...

> > Reading the issue + report gives the impression that the testing has been more thorough than the report indicates.
> 
> It seems that the wording used in the report is not understood although it covers exactly above questions.
> 
> > Please remember that someone reading this report may not be aware of the context, and will probably find it confusing.
> 
> Above report tries to answer exactly all functions that are asked for. Not more.
> 
> > Please be more explicit, and answer all the questions with as much details as required, and note what is still unknown or impossible to know.
> > As it appears this is at least partially tested, I'll allow 48h hours more for adding the results.
> 
> This seems to be a matter of words only. If it helps I will paste the questions into the report directly.

Thank you, it was partially a matter of words, and partially a matter of me being blind :D 

For the former, I think it's fair to expect that a report contains all necessary information, and can be understood on it's own without any extra context. Wrt the latter, I can only apologize...

**Review by bwhm — APPROVED** [review]
With the latest commit, and my increased reading comprehension, I'm going to grade this as fully completed.

It would be nice if you cleaned up the MacOS/iOS section a bit, but I'll close the bounty nevertheless.

**Comment by traumschule** [comment]
> Thank you, it was partially a matter of words, and partially a matter of me being blind :D

Haha, thanks for clarifying :)

968ea89 is the best I can do. Anybody who knows more about this extension on MacOS / iOS please create another PR!

**Pull request merged**
