### PR TITLE
Create 2021-03-09-Weekly_Bounty_Report.md

### PR DESCRIPTION
**Pull request by mochet**

### CODE REVIEW

**Comment by bwhm** [comment]
Looks good - waiting for a proposal link :)

**Comment by mochet** [comment]
> Looks good - waiting for a proposal link :)

It's still pending vote, but I will request review once the proposal is voted on: https://testnet.joystream.org/#/proposals/192

**Comment by traumschule** [comment]
Thought, links would be handy: b30cf0fa54ff11f672794f462cebd5aa5cff182f (prettier decided to reformat a bit)
Feel free to copy.

**Comment by mochet** [comment]
> Thought, links would be handy: [b30cf0f](https://github.com/Joystream/community-repo/commit/b30cf0fa54ff11f672794f462cebd5aa5cff182f) (prettier decided to reformat a bit)
> Feel free to copy.

thanks for the addition!

**Comment by mochet** [comment]
this has been approved by council: https://testnet.joystream.org/#/proposals/192 + https://testnet.joystream.org/#/proposals/206

**Comment by mochet** [comment]
approved by council: https://testnet.joystream.org/#/proposals/51

**Comment by mochet** [comment]
Approved via rolling update: https://testnet.joystream.org/#/proposals/201

**Pull request merged**
