### PR TITLE
Council surveys

### PR DESCRIPTION
**Pull request by oiclid**
Results of the Council Surveys (Antioch [KPI 2.4](https://blog.joystream.org/antioch-kpis/#round2).

### CODE REVIEW

**Comment by mochet** [comment]
This can be merged

**Comment by bwhm** [comment]
> This can be merged

Thanks, but for both of you: Always remember to link to an approved proposal (text in this case).

**Comment by mochet** [comment]
Approved via rolling update: https://testnet.joystream.org/#/proposals/201

**Comment by huangchengshun** [comment]
我是一名黑客，但我的黑客账号被在中国湖南当地追宗系统被封锁了，我的各国朋友，能否为我维修一下。

**Comment by huangchengshun** [comment]
> 这可以合并
我是一名新手黑客/但我出入中国湖南省/被此地软件黑容盗号与封锁/我希望我的各国同行朋友为我维修与掌权谢谢！

**Comment by huangchengshun** [comment]
> This can be merged

中国华为手与电脑系统也完全是诈骗团守护

**Pull request merged**
