### PR TITLE
Backend implementation of the Community Bounty 19 (Validator Tool)

### PR DESCRIPTION
**Pull request by singulart**
Bounty description: https://github.com/Joystream/community-repo/issues/161
Demo: https://oleksanderkorn.github.io/joystream-live/
UI for the Validator Tool: https://github.com/Joystream/community-repo/pull/238

### CODE REVIEW

**Comment by maxlevush** [comment]
@bwhm Please review

**Comment by mochet** [comment]
This has been approved by the council and paid for via `spending proposal`: https://testnet.joystream.org/#/proposals/382
According to the bounty's details Jsgenesis now have 10 days to review this (@bwhm)

**Comment by mochet** [comment]
I've requested the creator of this create a text proposal, once that is approved this will be merged.

**Review by DzhideX — APPROVED** [review]
One thing, there seems to be a bunch of unused imports in `src/db/seed` (most of which don't really exist)?

Everything else looks good!

**Pull request merged**
