### PR TITLE
Add council 42 minutes & tokenomics report

### PR DESCRIPTION
**Pull request by freakstatic**

### CODE REVIEW

**Comment by freakstatic** [comment]
https://testnet.joystream.org/#/proposals/1157

**Comment by Ilichhh** [comment]
~~Sumer~~ `Giza - Council Election Round #44  - Performance Review and Minutes`
:wink:

**Comment by freakstatic** [comment]
> 

thanks!

**Comment by freakstatic** [comment]
> ~Sumer~ `Giza - Council Election Round #44 - Performance Review and Minutes` wink

thanks!

**Comment by igrexac** [comment]
> https://testnet.joystream.org/#/proposals/1157

Approved

**Pull request merged**
