### PR TITLE
Community Bounty no.17 - Discord Video Bot

### PR DESCRIPTION
**Pull request by singulart**
The implementation of a bot that is expected to fulfil the requirements laid out [here](https://github.com/Joystream/community-repo/issues/151) 

Example of the bot announcement: https://imgur.com/a/MXPkC2z

Supported data points: 

- video ID
- video title
- video description, 
- video category, 
- channel author, 
- license, 
- video URL, 
- category URL, 
- video duration

Tags are not supported, because this feature is not yet implemented in Joystream Studio.

### CODE REVIEW

**Comment by freakstatic** [comment]
Mine "Developer mode" was in User Settings -> Advanced -> Developer Mode.

Got this error after uploading this video (https://play.joystream.org/video/520):
`TypeError: Cannot read property 'liaison' of null at joystreamvideobot/lib/src/bot.js:48:108`


Note: 
Node 16 seems to be required

**Comment by freakstatic** [comment]
By commenting the `setAuthor` I was able to test it and seems to post on discord just fine! 
Great job :+1:

**Comment by freakstatic** [comment]
> Mine "Developer mode" was in User Settings -> Advanced -> Developer Mode.
> 
> Got this error after uploading this video (https://play.joystream.org/video/520):
> `TypeError: Cannot read property 'liaison' of null at joystreamvideobot/lib/src/bot.js:48:108`
> 
> Note:
> Node 16 seems to be required

oh seems to be because my channel doesn't have an avatar :)

**Comment by singulart** [comment]
> Got this error after uploading this video (https://play.joystream.org/video/520):
> `TypeError: Cannot read property 'liaison' of null at joystreamvideobot/lib/src/bot.js:48:108`

Your channel has no avatar, this was the root cause of an issue. I'll try to fix this today

**Comment by freakstatic** [comment]
I think that is a bit important to clear the `ids` set
probably not a issue but after various months of the bot running that set will keep increasing and consuming more memory...
I think you can remove the video from the set if the `createdAgo` is higher than the video "uploaded date" the next iteration will not catch that video anyway :)

**Comment by singulart** [comment]
> I think that is a bit important to clear the `ids` set
> probably not a issue but after various months of the bot running that set will keep increasing and consuming more memory...
> I think you can remove the video from the set if the `createdAgo` is higher than the video "uploaded date" the next iteration will not catch that video anyway :)

Agreed

**Comment by freakstatic** [comment]
LGTM! :+1:

**Comment by mochet** [comment]
this was approved by the council in the following proposal: https://testnet.joystream.org/#/proposals/154

**Comment by mochet** [comment]
@bwhm as this involves code I won't merge it and will wait for your review

**Review by bwhm — COMMENTED** [review]
Looks great @singulart!

Was about to test deploy it now, but I get:

`this integration is private. only the application owner can add it. `

I assume this means only the **bot owner**, not the server owner?

**Comment by singulart** [comment]
Yes, the bot is an application refered to in this message I think

**Comment by bwhm** [comment]
> Yes, the bot is an application refered to in this message I think

Thanks for the quick reply. Are you able to grant us the permission required?

**Comment by singulart** [comment]
You don't need any specific permission from me) My assumption was that Jsgenesis would create the bot in discord guided by the instructions in the community repo: https://github.com/Joystream/community-repo/tree/master/community-contributions/discordbot

**Comment by bwhm** [comment]
Sorry for the confusion, I thought it was already deployed as I got a link for it earlier :)

**Review by bwhm — CHANGES_REQUESTED** [review]
Seems to work well, but I'm seeing some issues:

#### Deployment issues
Running failed due to `replaceAll` I had to manually add it with
`yarn add string.prototype.replaceall`

Then, the build failed before I created a new file:
`node_modules/string.prototype.replaceall/index.d.ts`
with
`declare module 'string.prototype.replaceall';`

#### Errors

I'm getting this error all the time:
```
Video 1853 already announced. 
TypeError: Cannot read property 'metadata' of null
    at /home/joystream/singulart-community-repo/community-contributions/joystreamvideobot/lib/src/bot.js:55:85
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async main (/home/joystream/singulart-community-repo/community-contributions/joystreamvideobot/lib/src/bot.js:33:9)
```

It doesn't crash, but I don't think it's great to have it running like that.

---

These are rather small issues in the grand scheme of things, but would be great if you could fix them :)

**Comment by singulart** [comment]
Deployment issue mentioned can be fixed by upgrading the node version, I believe. 

I will look into the missing metadata

**Comment by singulart** [comment]
Comments of @bwhm were addressed.

**Review by bwhm — APPROVED** [review]
Thanks a lot for the quick fixes!

**Pull request merged**
